/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projeto_17_valentin;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author ValentinGomes
 */
public class Usuario extends javax.swing.JFrame {

    /**
     * Creates new form Usuario
     */
    public Usuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlbl_cadastro = new javax.swing.JLabel();
        jlbl_nomeCadastro = new javax.swing.JLabel();
        jlbl_cpfCadastro = new javax.swing.JLabel();
        jlbl_telefoneCadastro = new javax.swing.JLabel();
        jtxtf_nomeCadastro = new javax.swing.JTextField();
        jtxtf_cpfCadastro = new javax.swing.JTextField();
        jtxtf_telefoneCadastro = new javax.swing.JTextField();
        jlbl_exibir = new javax.swing.JLabel();
        jlbl_idExibir = new javax.swing.JLabel();
        jtxtf_idExibir = new javax.swing.JTextField();
        jbtn_pesquisarExibir = new javax.swing.JButton();
        jlbl_nomeExibir = new javax.swing.JLabel();
        jlbl_atualizar = new javax.swing.JLabel();
        jlbl_nomeAtualizar = new javax.swing.JLabel();
        jlbl_cpfAtualizar = new javax.swing.JLabel();
        jlbl_telefoneAtualizar = new javax.swing.JLabel();
        jtxtf_nomeAtualizar = new javax.swing.JTextField();
        jtxtf_cpfAtualizar = new javax.swing.JTextField();
        jtxtf_telefoneAtualizar = new javax.swing.JTextField();
        jlbl_idAtualizar = new javax.swing.JLabel();
        jtxtf_idAtualizar = new javax.swing.JTextField();
        jbtn_atualizar = new javax.swing.JButton();
        jlbl_excluir = new javax.swing.JLabel();
        jlbl_idExcluir = new javax.swing.JLabel();
        jtxtf_idExcluir = new javax.swing.JTextField();
        jbtn_excluir = new javax.swing.JButton();
        jbtn_incluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlbl_cadastro.setText("CADASTRO");
        jPanel1.add(jlbl_cadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, -1));

        jlbl_nomeCadastro.setText("NOME:");
        jPanel1.add(jlbl_nomeCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jlbl_cpfCadastro.setText("CPF:");
        jPanel1.add(jlbl_cpfCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jlbl_telefoneCadastro.setText("TELEFONE:");
        jPanel1.add(jlbl_telefoneCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));
        jPanel1.add(jtxtf_nomeCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 100, 30));
        jPanel1.add(jtxtf_cpfCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 100, -1));
        jPanel1.add(jtxtf_telefoneCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 100, -1));

        jlbl_exibir.setText("EXIBIR");
        jPanel1.add(jlbl_exibir, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, -1, -1));

        jlbl_idExibir.setText("ID:");
        jPanel1.add(jlbl_idExibir, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, -1, -1));
        jPanel1.add(jtxtf_idExibir, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, 100, -1));

        jbtn_pesquisarExibir.setText("PESQUISAR");
        jbtn_pesquisarExibir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_pesquisarExibirActionPerformed(evt);
            }
        });
        jPanel1.add(jbtn_pesquisarExibir, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, -1, -1));

        jlbl_nomeExibir.setText("nome");
        jPanel1.add(jlbl_nomeExibir, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, -1, -1));

        jlbl_atualizar.setText("ATUALIZAR");
        jPanel1.add(jlbl_atualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, -1, -1));

        jlbl_nomeAtualizar.setText("NOME:");
        jPanel1.add(jlbl_nomeAtualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, -1));

        jlbl_cpfAtualizar.setText("CPF:");
        jPanel1.add(jlbl_cpfAtualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, -1, -1));

        jlbl_telefoneAtualizar.setText("TELEFONE:");
        jPanel1.add(jlbl_telefoneAtualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, -1, -1));
        jPanel1.add(jtxtf_nomeAtualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, 100, 30));
        jPanel1.add(jtxtf_cpfAtualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 380, 100, -1));
        jPanel1.add(jtxtf_telefoneAtualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 410, 100, -1));

        jlbl_idAtualizar.setText("ID:");
        jPanel1.add(jlbl_idAtualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));
        jPanel1.add(jtxtf_idAtualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, 100, -1));

        jbtn_atualizar.setText("ATUALIZAR");
        jbtn_atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_atualizarActionPerformed(evt);
            }
        });
        jPanel1.add(jbtn_atualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 450, -1, -1));

        jlbl_excluir.setText("EXCLUIR");
        jPanel1.add(jlbl_excluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 270, -1, -1));

        jlbl_idExcluir.setText("ID:");
        jPanel1.add(jlbl_idExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 320, -1, -1));
        jPanel1.add(jtxtf_idExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 320, 90, -1));

        jbtn_excluir.setText("EXCLUIR");
        jbtn_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_excluirActionPerformed(evt);
            }
        });
        jPanel1.add(jbtn_excluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 370, -1, -1));

        jbtn_incluir.setText("INCLUIR");
        jbtn_incluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_incluirActionPerformed(evt);
            }
        });
        jPanel1.add(jbtn_incluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn_incluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_incluirActionPerformed
        try {
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/cadastro", "root", "10071998");
            PreparedStatement insert = conn.prepareStatement("INSERT INTO pessoa(nome, cpf , telefone) VALUES (?, ? , ?)");
            insert.setString(1, jtxtf_nomeCadastro.getText());
            insert.setString(2, jtxtf_cpfCadastro.getText());
            insert.setString(3, jtxtf_telefoneCadastro.getText());
            
            int affected = insert.executeUpdate();
            insert.close();
            conn.close();
        } catch (SQLException e) {
            System.out.print(e.getMessage());
        }
    }//GEN-LAST:event_jbtn_incluirActionPerformed

    private void jbtn_pesquisarExibirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_pesquisarExibirActionPerformed
        try {
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/cadastro", "root", "10071998");
            PreparedStatement select = conn.prepareStatement("SELECT nome FROM pessoa WHERE id = ?");
            select.setString(1, jtxtf_idExibir.getText());
            
            ResultSet resultSet = select.executeQuery();
            
            if(resultSet.next()){
                String nome = resultSet.getString("nome");
                jlbl_nomeExibir.setText(nome);
            }
            else{
                jlbl_nomeExibir.setText("Pessoa nao encontrada");
            }
            
            int affected = select.executeUpdate();
            resultSet.close();
            select.close();
            conn.close();
        } catch (SQLException e) {
            System.out.print(e.getMessage());
        }
    }//GEN-LAST:event_jbtn_pesquisarExibirActionPerformed

    private void jbtn_atualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_atualizarActionPerformed
        try {
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/cadastro", "root", "10071998");
            PreparedStatement update = conn.prepareStatement("UPDATE pessoa SET nome = ?, cpf = ?, telefone = ? WHERE id = ?");
            update.setString(1, jtxtf_nomeAtualizar.getText());
            update.setString(2, jtxtf_cpfAtualizar.getText());
            update.setString(3, jtxtf_telefoneAtualizar.getText());
            update.setString(4, jtxtf_idAtualizar.getText());
            
            int affected = update.executeUpdate();
            update.close();
            conn.close();
        } catch (SQLException e) {
            System.out.print(e.getMessage());
        }
    }//GEN-LAST:event_jbtn_atualizarActionPerformed

    private void jbtn_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_excluirActionPerformed
        try {
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/cadastro", "root", "10071998");
            PreparedStatement delete = conn.prepareStatement("DELETE FROM pessoa WHERE id = ?");
            delete.setString(1, jtxtf_idExcluir.getText());
            
            int affected = delete.executeUpdate();
            delete.close();
            conn.close();
        } catch (SQLException e) {
            System.out.print(e.getMessage());
        }
    }//GEN-LAST:event_jbtn_excluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Usuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtn_atualizar;
    private javax.swing.JButton jbtn_excluir;
    private javax.swing.JButton jbtn_incluir;
    private javax.swing.JButton jbtn_pesquisarExibir;
    private javax.swing.JLabel jlbl_atualizar;
    private javax.swing.JLabel jlbl_cadastro;
    private javax.swing.JLabel jlbl_cpfAtualizar;
    private javax.swing.JLabel jlbl_cpfCadastro;
    private javax.swing.JLabel jlbl_excluir;
    private javax.swing.JLabel jlbl_exibir;
    private javax.swing.JLabel jlbl_idAtualizar;
    private javax.swing.JLabel jlbl_idExcluir;
    private javax.swing.JLabel jlbl_idExibir;
    private javax.swing.JLabel jlbl_nomeAtualizar;
    private javax.swing.JLabel jlbl_nomeCadastro;
    private javax.swing.JLabel jlbl_nomeExibir;
    private javax.swing.JLabel jlbl_telefoneAtualizar;
    private javax.swing.JLabel jlbl_telefoneCadastro;
    private javax.swing.JTextField jtxtf_cpfAtualizar;
    private javax.swing.JTextField jtxtf_cpfCadastro;
    private javax.swing.JTextField jtxtf_idAtualizar;
    private javax.swing.JTextField jtxtf_idExcluir;
    private javax.swing.JTextField jtxtf_idExibir;
    private javax.swing.JTextField jtxtf_nomeAtualizar;
    private javax.swing.JTextField jtxtf_nomeCadastro;
    private javax.swing.JTextField jtxtf_telefoneAtualizar;
    private javax.swing.JTextField jtxtf_telefoneCadastro;
    // End of variables declaration//GEN-END:variables
}
