/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projeto_cadastro_campos;

/**
 *
 * @author v.gomes
 */
public class EXIBIR_OCULTAR_MENSAGEM extends javax.swing.JFrame {

    /**
     * Creates new form EXIBIR_OCULTAR_MENSAGEM
     */
    
    public EXIBIR_OCULTAR_MENSAGEM() {
        
        initComponents();
        jlbl_conectado.setVisible(false);
        jlbl_desconectado.setVisible(false);
        jlbl_achou.setVisible(false);
        jbtn_ocultar.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlbl_conectado = new javax.swing.JLabel();
        jlbl_desconectado = new javax.swing.JLabel();
        jlbl_achou = new javax.swing.JLabel();
        jbtn_exibir = new javax.swing.JButton();
        jbtn_ocultar = new javax.swing.JButton();
        jlbl_seleciona = new javax.swing.JLabel();
        jlbl_radio = new javax.swing.JLabel();
        jlbl_checkbox = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jcmb_item = new javax.swing.JComboBox<>();
        jCheckBox1 = new javax.swing.JCheckBox();
        jbtn_item = new javax.swing.JButton();
        jbtn_radio_check = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlbl_conectado.setText("Conectado");

        jlbl_desconectado.setText("Desconectado");

        jlbl_achou.setText("ACHOU");

        jbtn_exibir.setText("EXIBIR");
        jbtn_exibir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_exibirActionPerformed(evt);
            }
        });

        jbtn_ocultar.setText("OCULTAR");
        jbtn_ocultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_ocultarActionPerformed(evt);
            }
        });

        jlbl_seleciona.setText("SELECIONA");

        jlbl_radio.setText("RadioButtom Selecionado");

        jlbl_checkbox.setText("CheckBox Selecionado");

        jRadioButton1.setText("jRadioButton1");

        jcmb_item.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jCheckBox1.setText("jCheckBox1");

        jbtn_item.setText("ITEM");
        jbtn_item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_itemActionPerformed(evt);
            }
        });

        jbtn_radio_check.setText("Radio/Check");
        jbtn_radio_check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_radio_checkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(jlbl_desconectado))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(jlbl_conectado))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbl_radio)
                            .addComponent(jlbl_achou)
                            .addComponent(jlbl_seleciona)
                            .addComponent(jcmb_item, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlbl_checkbox)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jbtn_exibir)
                        .addGap(30, 30, 30)
                        .addComponent(jbtn_ocultar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton1)
                            .addComponent(jbtn_item))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbtn_radio_check)
                            .addComponent(jCheckBox1))))
                .addContainerGap(112, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jlbl_conectado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbl_desconectado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbl_achou)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn_exibir)
                    .addComponent(jbtn_ocultar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbl_seleciona)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbl_radio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbl_checkbox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn_item)
                    .addComponent(jbtn_radio_check))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jCheckBox1))
                .addGap(19, 19, 19)
                .addComponent(jcmb_item, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn_exibirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_exibirActionPerformed
        jlbl_achou.setVisible(true);
        jlbl_conectado.setVisible(true);
        jlbl_desconectado.setVisible(false);
        jbtn_ocultar.setVisible(true);
    }//GEN-LAST:event_jbtn_exibirActionPerformed

    private void jbtn_ocultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_ocultarActionPerformed
        jlbl_achou.setVisible(false);
        jlbl_conectado.setVisible(false);
        jlbl_desconectado.setVisible(true);
        jbtn_ocultar.setVisible(true);
    }//GEN-LAST:event_jbtn_ocultarActionPerformed

    private void jbtn_itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_itemActionPerformed
        jlbl_seleciona.setVisible(true);
    }//GEN-LAST:event_jbtn_itemActionPerformed

    private void jbtn_radio_checkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_radio_checkActionPerformed
        jlbl_radio.setVisible(true);
        jlbl_checkbox.setVisible(true);
    }//GEN-LAST:event_jbtn_radio_checkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EXIBIR_OCULTAR_MENSAGEM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EXIBIR_OCULTAR_MENSAGEM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EXIBIR_OCULTAR_MENSAGEM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EXIBIR_OCULTAR_MENSAGEM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EXIBIR_OCULTAR_MENSAGEM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JButton jbtn_exibir;
    private javax.swing.JButton jbtn_item;
    private javax.swing.JButton jbtn_ocultar;
    private javax.swing.JButton jbtn_radio_check;
    private javax.swing.JComboBox<String> jcmb_item;
    private javax.swing.JLabel jlbl_achou;
    private javax.swing.JLabel jlbl_checkbox;
    private javax.swing.JLabel jlbl_conectado;
    private javax.swing.JLabel jlbl_desconectado;
    private javax.swing.JLabel jlbl_radio;
    private javax.swing.JLabel jlbl_seleciona;
    // End of variables declaration//GEN-END:variables
}
