/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projeto_cadastro_campos;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;


/**
 *
 * @author v.gomes
 */
public class PRIMEIRO_CAMPO extends javax.swing.JFrame {

    /**
     * Creates new form PRIMEIRO_CAMPO
     */
    public PRIMEIRO_CAMPO() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlbl_luzes_dianteiras = new javax.swing.JLabel();
        jtxtf_nome = new javax.swing.JTextField();
        jlbl_luzes_taseiras = new javax.swing.JLabel();
        jtxtf_telefone = new javax.swing.JTextField();
        jlbl_pisca_alerta = new javax.swing.JLabel();
        jtxtf_cpf = new javax.swing.JTextField();
        jlbl_titulo = new javax.swing.JLabel();
        jlbl_sistema_eletrico = new javax.swing.JLabel();
        jlbl_luz_freio = new javax.swing.JLabel();
        jlbl_giroflex = new javax.swing.JLabel();
        jlbl_alarme_re = new javax.swing.JLabel();
        jlbl_sistema_partida = new javax.swing.JLabel();
        jlbl_buzina = new javax.swing.JLabel();
        jlbl_sistema_hidraulico = new javax.swing.JLabel();
        jlbl_nivel_oleo_hidraulico = new javax.swing.JLabel();
        jlbl_mangueiras_geral = new javax.swing.JLabel();
        jlbl_vazamento_oleo = new javax.swing.JLabel();
        jlbl_cilindro_elevacao = new javax.swing.JLabel();
        jlbl_cilindro_inclinacao = new javax.swing.JLabel();
        jlbl_mangueira_lanca = new javax.swing.JLabel();
        jlbl_mangueira_direcao = new javax.swing.JLabel();
        jlbl_oleo_transmissao = new javax.swing.JLabel();
        jlbl_estrutura_mecanica = new javax.swing.JLabel();
        jlbl_apresenta_trinca = new javax.swing.JLabel();
        jlbl_deformacao_estrutura = new javax.swing.JLabel();
        jlbl_deformacao_lataria = new javax.swing.JLabel();
        jlbl_lubrificacao_folga = new javax.swing.JLabel();
        jlbl_motor = new javax.swing.JLabel();
        jlbl_oleo_motor = new javax.swing.JLabel();
        jlbl_vazamento_motor = new javax.swing.JLabel();
        jlbl_limpeza_radiador = new javax.swing.JLabel();
        jlbl_nivel_agua = new javax.swing.JLabel();
        jlbl_pneus = new javax.swing.JLabel();
        jlbl_pneu_dianteiro = new javax.swing.JLabel();
        jlbl_pneu_traseiro = new javax.swing.JLabel();
        jbtn_salvar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlbl_luzes_dianteiras.setText("Luzes Dianteiras");

        jtxtf_nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtf_nomeActionPerformed(evt);
            }
        });

        jlbl_luzes_taseiras.setText("Luzes Traseiras");

        jlbl_pisca_alerta.setText("Pisca Alerta");

        jlbl_titulo.setText("CHECKLIST PÁ CARREGADEIRA");

        jlbl_sistema_eletrico.setText("SISTEMA ELÉTRICO");

        jlbl_luz_freio.setText("Luz de Freio");

        jlbl_giroflex.setText("Giroflex");

        jlbl_alarme_re.setText("Alarme de Ré");

        jlbl_sistema_partida.setText("Sistema de partida");

        jlbl_buzina.setText("Buzina");

        jlbl_sistema_hidraulico.setText("SISTEMA HIDRÁULICO");

        jlbl_nivel_oleo_hidraulico.setText("Nível Óleo Hidráulico");

        jlbl_mangueiras_geral.setText("Mangueiras em Geral");

        jlbl_vazamento_oleo.setText("Vazamento de Óleo");

        jlbl_cilindro_elevacao.setText("Cilindro de elevação");

        jlbl_cilindro_inclinacao.setText("Cilindro de Inclinação");

        jlbl_mangueira_lanca.setText("Mangueira da Lança");

        jlbl_mangueira_direcao.setText("Mangueira do Cilindro da Direção");

        jlbl_oleo_transmissao.setText("Nível Óleo Transmissão");

        jlbl_estrutura_mecanica.setText("ESTRUTURA MECÂNICA");

        jlbl_apresenta_trinca.setText("Apresenta Trincas");

        jlbl_deformacao_estrutura.setText("Apresenta Deformação na Estrutura");

        jlbl_deformacao_lataria.setText("Apresenta Deformação na Lataria");

        jlbl_lubrificacao_folga.setText("Lubrificação, Pinos, Articulação e Possíveis Folgas");

        jlbl_motor.setText("MOTOR");

        jlbl_oleo_motor.setText("Nível Óleo de motor");

        jlbl_vazamento_motor.setText("Vazamento no Motor");

        jlbl_limpeza_radiador.setText("Limpeza do Radiador");

        jlbl_nivel_agua.setText("Nível de água do Reservatório");

        jlbl_pneus.setText("PNEUS");

        jlbl_pneu_dianteiro.setText("Calibração e Conservação Pneu Dianteiro ");

        jlbl_pneu_traseiro.setText("Calibração e Conservação Pneu Traseiro");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlbl_titulo)
                .addGap(113, 113, 113))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(jlbl_estrutura_mecanica))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(jlbl_motor)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jlbl_luzes_dianteiras))
                            .addComponent(jlbl_luzes_taseiras)
                            .addComponent(jlbl_luz_freio)
                            .addComponent(jlbl_pisca_alerta))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtf_telefone, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtxtf_cpf, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlbl_sistema_hidraulico)
                                    .addComponent(jtxtf_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlbl_sistema_eletrico))
                                .addGap(0, 54, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbl_pneu_traseiro)
                            .addComponent(jlbl_limpeza_radiador)
                            .addComponent(jlbl_vazamento_motor)
                            .addComponent(jlbl_oleo_motor)
                            .addComponent(jlbl_lubrificacao_folga)
                            .addComponent(jlbl_deformacao_lataria)
                            .addComponent(jlbl_deformacao_estrutura)
                            .addComponent(jlbl_apresenta_trinca)
                            .addComponent(jlbl_oleo_transmissao)
                            .addComponent(jlbl_mangueira_direcao)
                            .addComponent(jlbl_mangueira_lanca)
                            .addComponent(jlbl_cilindro_inclinacao)
                            .addComponent(jlbl_cilindro_elevacao)
                            .addComponent(jlbl_vazamento_oleo)
                            .addComponent(jlbl_mangueiras_geral)
                            .addComponent(jlbl_nivel_oleo_hidraulico)
                            .addComponent(jlbl_buzina)
                            .addComponent(jlbl_sistema_partida)
                            .addComponent(jlbl_alarme_re)
                            .addComponent(jlbl_giroflex)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jlbl_pneus)
                                .addComponent(jlbl_nivel_agua))
                            .addComponent(jlbl_pneu_dianteiro))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbl_titulo)
                .addGap(27, 27, 27)
                .addComponent(jlbl_sistema_eletrico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbl_luzes_dianteiras)
                    .addComponent(jtxtf_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtf_telefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbl_luzes_taseiras))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtf_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbl_luz_freio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbl_pisca_alerta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbl_giroflex)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbl_alarme_re)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbl_sistema_partida)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbl_buzina)
                .addGap(16, 16, 16)
                .addComponent(jlbl_sistema_hidraulico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbl_nivel_oleo_hidraulico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbl_mangueiras_geral)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbl_vazamento_oleo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbl_cilindro_elevacao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbl_cilindro_inclinacao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbl_mangueira_lanca)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbl_mangueira_direcao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbl_oleo_transmissao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbl_estrutura_mecanica)
                .addGap(11, 11, 11)
                .addComponent(jlbl_apresenta_trinca)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbl_deformacao_estrutura)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbl_deformacao_lataria)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbl_lubrificacao_folga)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbl_motor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbl_oleo_motor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbl_vazamento_motor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbl_limpeza_radiador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbl_nivel_agua)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbl_pneus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbl_pneu_dianteiro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbl_pneu_traseiro)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jbtn_salvar.setText("SALVAR");
        jbtn_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_salvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtn_salvar)
                .addGap(163, 163, 163))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(jbtn_salvar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtf_nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtf_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtf_nomeActionPerformed

    private void jbtn_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_salvarActionPerformed
        try {
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/cadastro_campos", "root", "");
            PreparedStatement insert = conn.prepareStatement("INSERT INTO primeiro_campo(nome, telefone, cpf) VALUES (?, ? , ?)");
            insert.setString(1, jtxtf_nome.getText());
            insert.setString(2, jtxtf_telefone.getText());
            insert.setString(3, jtxtf_cpf.getText());
            
            int affected = insert.executeUpdate();
            insert.close();
            conn.close();
        } catch (SQLException e) {
            System.out.print(e.getMessage());
        }
    }//GEN-LAST:event_jbtn_salvarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PRIMEIRO_CAMPO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PRIMEIRO_CAMPO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PRIMEIRO_CAMPO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PRIMEIRO_CAMPO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PRIMEIRO_CAMPO().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtn_salvar;
    private javax.swing.JLabel jlbl_alarme_re;
    private javax.swing.JLabel jlbl_apresenta_trinca;
    private javax.swing.JLabel jlbl_buzina;
    private javax.swing.JLabel jlbl_cilindro_elevacao;
    private javax.swing.JLabel jlbl_cilindro_inclinacao;
    private javax.swing.JLabel jlbl_deformacao_estrutura;
    private javax.swing.JLabel jlbl_deformacao_lataria;
    private javax.swing.JLabel jlbl_estrutura_mecanica;
    private javax.swing.JLabel jlbl_giroflex;
    private javax.swing.JLabel jlbl_limpeza_radiador;
    private javax.swing.JLabel jlbl_lubrificacao_folga;
    private javax.swing.JLabel jlbl_luz_freio;
    private javax.swing.JLabel jlbl_luzes_dianteiras;
    private javax.swing.JLabel jlbl_luzes_taseiras;
    private javax.swing.JLabel jlbl_mangueira_direcao;
    private javax.swing.JLabel jlbl_mangueira_lanca;
    private javax.swing.JLabel jlbl_mangueiras_geral;
    private javax.swing.JLabel jlbl_motor;
    private javax.swing.JLabel jlbl_nivel_agua;
    private javax.swing.JLabel jlbl_nivel_oleo_hidraulico;
    private javax.swing.JLabel jlbl_oleo_motor;
    private javax.swing.JLabel jlbl_oleo_transmissao;
    private javax.swing.JLabel jlbl_pisca_alerta;
    private javax.swing.JLabel jlbl_pneu_dianteiro;
    private javax.swing.JLabel jlbl_pneu_traseiro;
    private javax.swing.JLabel jlbl_pneus;
    private javax.swing.JLabel jlbl_sistema_eletrico;
    private javax.swing.JLabel jlbl_sistema_hidraulico;
    private javax.swing.JLabel jlbl_sistema_partida;
    private javax.swing.JLabel jlbl_titulo;
    private javax.swing.JLabel jlbl_vazamento_motor;
    private javax.swing.JLabel jlbl_vazamento_oleo;
    private javax.swing.JTextField jtxtf_cpf;
    private javax.swing.JTextField jtxtf_nome;
    private javax.swing.JTextField jtxtf_telefone;
    // End of variables declaration//GEN-END:variables
}
